schema-version = 1

[package]
title = "Mission Control"
version = "0.2.0"
build_number = 5
id = "com.kellner.missioncontrol"
icon = "@image/icon.png"

[os.version]
min = "1.2"
target = "1.2"

[needs]
[[needs.module]]
id = "/com.amazon.vega.os@IVega_1_2"

[[needs.module]]
id = "/com.amazon.kepler.keplerscript_4@IKeplerScript_0"

[[needs.module]]
id = "/com.amazon.kepler.webview_4@IWebview_4"



[components]
[[components.interactive]]
id = "com.kellner.missioncontrol.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
# Native dashboard: no WebView, no media playback. Minimal services.
# Accessibility support
[[wants.service]]
id = "com.amazon.kepler.ucc.publisher"

# Enable Group-IPC
[[wants.service]]
id = "com.amazon.gipc.uuid.*"
[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*" 

# You may add other services as needed
